dist: trusty
sudo: required

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y apt-utils
  - sudo apt-get install -y wget
  - sudo apt-get install -y xz-utils
  - sudo apt-get install -y build-essential
  - sudo apt-get install -y libsqlite3-dev
  - sudo apt-get install -y libreadline-dev
  - sudo apt-get install -y libssl-dev
  - sudo apt-get install -y libffi-dev
  - sudo apt-get install -y openssl
  - sudo apt-get install -y net-tools
#  - sudo add-apt-repository -y ppa:jonathonf/python-3.6
  - sudo apt-get -qq update
  # Python
#  - sudo apt-get -y install python3.6
#  - sudo apt-get -y install python3.6-dev
#  - sudo apt-get -y install python3-pip
#  - sudo -H pip3 install -U pip setuptools
#  - echo "alias python=python3.6" >> ~/.bashrc
  # Mongo
#  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
#  - echo "deb [ arch=amd64 ] http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.4.list
#  - sudo apt-get -qq update
#  - sudo apt-get install -y mongodb-org
#  - sudo chown -R mongodb:mongodb /var/lib/mongodb
  # Allowing connections to other interfaces besides loopback
#  - sudo sed -i.bak '/bindIp/d' /etc/mongod.conf
#  - sudo service mongod start
  # Docker compose
#  - sudo curl -o /usr/local/bin/docker-compose -L "https://github.com/docker/compose/releases/download/1.11.2/docker-compose-$(uname -s)-$(uname -m)"
#  - sudo chmod +x /usr/local/bin/docker-compose
#  - docker-compose -v
  # PIP
#  - sudo cp pip.conf /etc/pip.conf
#  - cp ./.pypirc ~/.pypirc
  # Travis
  - gem install travis -v 1.8.8 --no-rdoc --no-ri

notifications:
  email:
    recipients:
      - magen-build@cisco.com
    on_success: always # default: change
    on_failure: always # default: always

services:
  - docker
language: python
#python:
#  - "3.6"
#  - "3.6-dev" # 3.6 development branch
# command to install dependencies
matrix:
  include:
    - python: 3.6
      env: TO_BUILD=NATIVE
    - python: 3.6
      env: TO_BUILD=DOCKER
  fast_finish: true

script:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
      helper_scripts/travis_trigger_dependent_builds.sh; fi;
    else
      echo $TRAVIS_BRANCH;
    fi
